apiVersion: agones.dev/v1
kind: GameServer
metadata:
  name: agones-bootstrap-guide-game-server
  generateName: agones-bootstrap-guide-game-server-
  annotations:
    agones.dev/dev-address: "127.0.0.1"
spec:
  ports:
    - name: default
      portPolicy: Static
      hostPort: 7777
      containerPort: 7777
  # The following is ignored but required due to validation.
  template:
    spec:
      containers:
        - name: agones-bootstrap-guide-game-server
          image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.32
          resources:
            requests:
              memory: 64Mi
              cpu: 20m
            limits:
              memory: 64Mi
              cpu: 20m
